- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
###############################################################################################
  - name: Create Resource Group
    azure_rm_resourcegroup:
      name: AnsibleTower3-ResourceGroup
      location: eastus
###############################################################################################
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: AnsibleTower3-ResourceGroup
      name: AnsibleTower3Vnet
      address_prefixes: "192.168.0.0/16"
###############################################################################################
  - name: Add subnet
    azure_rm_subnet:
      resource_group: AnsibleTower3-ResourceGroup
      name: AnsibleTower3Subnet
      address_prefix: "192.168.1.0/24"
      virtual_network: AnsibleTower3Vnet
############################################################################################### 
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: AnsibleTower3-ResourceGroup
      allocation_method: Static
      name: AnsibleTower3PublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
###############################################################################################
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: AnsibleTower3-ResourceGroup
      name: AnsibleTower3NetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
###############################################################################################
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: AnsibleTower3-ResourceGroup
      name: AnsibleTower3NIC
      virtual_network: AnsibleTower3Vnet
      subnet: AnsibleTower3Subnet
      public_ip_name: AnsibleTower3PublicIP
      security_group: AnsibleTower3NetworkSecurityGroup
###############################################################################################
  - name: Create VM as Linux-WebServer
    azure_rm_virtualmachine:
      resource_group: AnsibleTower3-ResourceGroup
      name: Linux-WebServer
      vm_size: Standard_DS1_v2
      admin_username: Kumarsu8
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/Kumarsu8/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqCvPWI9M6uLAMPHzCz8V5vFjkFF1rQoASRBOw8BN5n5F9/9mjyS40OGz2s3aq8wYGMRLQbp71REwN7RI9Pn73iTnyMapb8IvF/oHjUKr8mBFPhxtXhLtnZ9G3KnrFuZi2staDOZMRcD+8RhuGfKVm4n1VnkTujkHhQCod1cVHLNC/+8chABS6XaOWYWvZgmwCwQG/ihVnQNtjlQTX4p8Vv9/Ez81DLl0YK7X+pa5GCrPxr0exKotKBT1ABFuAwnWP2mo/+Li0IjmX7A3bKmD/a3Fcs7+dDuqdj8lEKVzHeJ9JAIw08wDP+1eOJ38aY/qoC04IYftq5CTnjQabT2Rb Sushant@INCHNLOCALMAC
      network_interfaces: AnsibleTower3NIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
###############################################################################################
###############################################################################################
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: AnsibleTower3-ResourceGroup
      name: AnsibleTower3NIC-1
      virtual_network: AnsibleTower3Vnet
      subnet: AnsibleTower3Subnet
      public_ip_name: AnsibleTower3PublicIP-1
      security_group: AnsibleTower3NetworkSecurityGroup
###############################################################################################
  - name: Create VM as Linux-DatabaseServer
    azure_rm_virtualmachine:
      resource_group: AnsibleTower3-ResourceGroup
      name: Linux-DatabaseServer
      vm_size: Standard_DS1_v2
      admin_username: Kumarsu8
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/Kumarsu8/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqCvPWI9M6uLAMPHzCz8V5vFjkFF1rQoASRBOw8BN5n5F9/9mjyS40OGz2s3aq8wYGMRLQbp71REwN7RI9Pn73iTnyMapb8IvF/oHjUKr8mBFPhxtXhLtnZ9G3KnrFuZi2staDOZMRcD+8RhuGfKVm4n1VnkTujkHhQCod1cVHLNC/+8chABS6XaOWYWvZgmwCwQG/ihVnQNtjlQTX4p8Vv9/Ez81DLl0YK7X+pa5GCrPxr0exKotKBT1ABFuAwnWP2mo/+Li0IjmX7A3bKmD/a3Fcs7+dDuqdj8lEKVzHeJ9JAIw08wDP+1eOJ38aY/qoC04IYftq5CTnjQabT2Rb Sushant@INCHNLOCALMAC
      network_interfaces: AnsibleTower3NIC-1
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
###############################################################################################